services:
  product-service:
    build: ./product-service
    ports:
      - '3002:3002'
    environment:
      - DATABASE_URL=postgres://postgres:YzkwNWJmZTAtNjQ4YS00ZTQzLWFiZjQt@localhost:54322/postgres
    depends_on:
      - product-db
  customer-service:
    build: ./customer-service
    ports:
      - '3005:3005'
    environment:
      - DATABASE_URL=postgres://postgres:YzkwNWJmZTAtNjQ4YS00ZTQzLWFiZjQt@localhost:54322/postgres
    depends_on:
      - product-db
  product-db:
    image: supabase/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YzkwNWJmZTAtNjQ4YS00ZTQzLWFiZjQt
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
